create table countries (
	id INTEGER NOT NULL PRIMARY KEY,
  country VARCHAR(60) NOT NULL
);
insert into countries (id, country) values (1, 'Brazil');
insert into countries (id, country) values (2, 'Japan');
insert into countries (id, country) values (3, 'Palestinian Territory');
insert into countries (id, country) values (4, 'China');
insert into countries (id, country) values (5, 'Trinidad and Tobago');
insert into countries (id, country) values (6, 'China');
insert into countries (id, country) values (7, 'Yemen');
insert into countries (id, country) values (8, 'Philippines');
insert into countries (id, country) values (9, 'Serbia');
insert into countries (id, country) values (10, 'China');
insert into countries (id, country) values (11, 'Armenia');
insert into countries (id, country) values (12, 'Philippines');
insert into countries (id, country) values (13, 'Brazil');
insert into countries (id, country) values (14, 'Russia');
insert into countries (id, country) values (15, 'Malaysia');
insert into countries (id, country) values (16, 'Indonesia');
insert into countries (id, country) values (17, 'France');
insert into countries (id, country) values (18, 'China');
insert into countries (id, country) values (19, 'Russia');
insert into countries (id, country) values (20, 'France');
insert into countries (id, country) values (21, 'Ghana');
insert into countries (id, country) values (22, 'Denmark');
insert into countries (id, country) values (23, 'Philippines');
insert into countries (id, country) values (24, 'Peru');
insert into countries (id, country) values (25, 'Iran');
insert into countries (id, country) values (26, 'Indonesia');
insert into countries (id, country) values (27, 'Bosnia and Herzegovina');
insert into countries (id, country) values (28, 'Papua New Guinea');
insert into countries (id, country) values (29, 'Philippines');
insert into countries (id, country) values (30, 'Colombia');
insert into countries (id, country) values (31, 'Venezuela');
insert into countries (id, country) values (32, 'Brazil');
insert into countries (id, country) values (33, 'Israel');
insert into countries (id, country) values (34, 'China');
insert into countries (id, country) values (35, 'Greece');
insert into countries (id, country) values (36, 'Chile');
insert into countries (id, country) values (37, 'Philippines');
insert into countries (id, country) values (38, 'Malaysia');
insert into countries (id, country) values (39, 'Russia');
insert into countries (id, country) values (40, 'Ukraine');
insert into countries (id, country) values (41, 'Portugal');
insert into countries (id, country) values (42, 'China');
insert into countries (id, country) values (43, 'Palestinian Territory');
insert into countries (id, country) values (44, 'South Africa');
insert into countries (id, country) values (45, 'China');
insert into countries (id, country) values (46, 'Indonesia');
insert into countries (id, country) values (47, 'China');
insert into countries (id, country) values (48, 'Philippines');
insert into countries (id, country) values (49, 'Kazakhstan');
insert into countries (id, country) values (50, 'France');
insert into countries (id, country) values (51, 'Indonesia');
insert into countries (id, country) values (52, 'China');
insert into countries (id, country) values (53, 'France');
insert into countries (id, country) values (54, 'Brazil');
insert into countries (id, country) values (55, 'Myanmar');
insert into countries (id, country) values (56, 'Poland');
insert into countries (id, country) values (57, 'Poland');
insert into countries (id, country) values (58, 'United States');
insert into countries (id, country) values (59, 'Tunisia');
insert into countries (id, country) values (60, 'Lebanon');
insert into countries (id, country) values (61, 'Lithuania');
insert into countries (id, country) values (62, 'Poland');
insert into countries (id, country) values (63, 'Ukraine');
insert into countries (id, country) values (64, 'Indonesia');
insert into countries (id, country) values (65, 'Czech Republic');
insert into countries (id, country) values (66, 'Brazil');
insert into countries (id, country) values (67, 'Sweden');
insert into countries (id, country) values (68, 'Philippines');
insert into countries (id, country) values (69, 'Russia');
insert into countries (id, country) values (70, 'Albania');
insert into countries (id, country) values (71, 'Brazil');
insert into countries (id, country) values (72, 'Indonesia');
insert into countries (id, country) values (73, 'China');
insert into countries (id, country) values (74, 'Ukraine');
insert into countries (id, country) values (75, 'Mexico');
insert into countries (id, country) values (76, 'China');
insert into countries (id, country) values (77, 'Canada');
insert into countries (id, country) values (78, 'China');
insert into countries (id, country) values (79, 'China');
insert into countries (id, country) values (80, 'South Africa');
insert into countries (id, country) values (81, 'Brazil');
insert into countries (id, country) values (82, 'Mexico');
insert into countries (id, country) values (83, 'Portugal');
insert into countries (id, country) values (84, 'United States');
insert into countries (id, country) values (85, 'China');
insert into countries (id, country) values (86, 'Iran');
insert into countries (id, country) values (87, 'Philippines');
insert into countries (id, country) values (88, 'South Korea');
insert into countries (id, country) values (89, 'Ireland');
insert into countries (id, country) values (90, 'Indonesia');
insert into countries (id, country) values (91, 'Ukraine');
insert into countries (id, country) values (92, 'Bosnia and Herzegovina');
insert into countries (id, country) values (93, 'Philippines');
insert into countries (id, country) values (94, 'Indonesia');
insert into countries (id, country) values (95, 'Sweden');
insert into countries (id, country) values (96, 'Poland');
insert into countries (id, country) values (97, 'China');
insert into countries (id, country) values (98, 'China');
insert into countries (id, country) values (99, 'Poland');
insert into countries (id, country) values (100, 'Czech Republic');
