create table orders (
	id BIGINT NOT NULL PRIMARY KEY,
  country_id BIGINT REFERENCES countries(id),
  first_name VARCHAR(50) NOT NULL,
  last_name VARCHAR(80) NOT NULL,
  street_address1 TEXT NOT NULL,
  street_address2 TEXT,
  province TEXT NULL,
  postal_code TEXT NULL,
  city TEXT NOT NULL,
  email_address TEXT UNIQUE NOT NULL,
  phone_number VARCHAR(50),
  company VARCHAR(80),
  payment_timestamp DATE NOT NULL,
  payment_method VARCHAR(50) NULL,
  payment_status VARCHAR(50) NOT NULL
);
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (1, 1, 'Cecil', 'Mallabon', '457 Toban Court', null, null, null, 'Eqlīd', 'cmallabon0@is.gd', '720-739-0999', null, '2019-07-28 11:43:20', 'bankcard', 'pending');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (2, 2, 'Andreana', 'Deegan', '5904 Ryan Trail', null, null, null, 'Savyon', 'adeegan1@accuweather.com', '466-274-3427', null, '2019-06-19 01:56:19', 'americanexpress', 'complete');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (3, 3, 'Laurel', 'Mowett', '77 Killdeer Way', null, null, '4515-093', 'Foz Sousa', 'lmowett2@salon.com', '375-598-5713', null, '2019-11-04 06:37:45', 'china-unionpay', 'complete');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (4, 4, 'Othelia', 'Adney', '06 Messerschmidt Junction', null, null, null, 'Bŭka', 'oadney3@amazon.de', '905-892-6775', null, '2019-09-25 12:50:28', 'jcb', 'inactive');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (5, 5, 'Royall', 'Craw', '80 Loftsgordon Drive', null, null, '10409', 'Berlin', 'rcraw4@ovh.net', '819-116-6278', null, '2019-08-03 14:45:34', 'mastercard', 'complete');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (6, 6, 'Waneta', 'MacDearmaid', '843 Waywood Junction', null, null, null, 'Kairouan', 'wmacdearmaid5@nps.gov', '478-240-6225', null, '2019-05-28 21:24:29', 'jcb', 'inactive');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (7, 7, 'Currey', 'Lyttle', '7709 Pine View Trail', null, null, null, 'Maiwang', 'clyttle6@biblegateway.com', '251-930-3617', null, '2019-08-23 10:42:36', 'americanexpress', 'inactive');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (8, 8, 'Thor', 'Hardiman', '644 Arizona Point', null, null, 'MD-5431', 'Saharna', 'thardiman7@biblegateway.com', '151-936-4865', null, '2018-11-19 05:46:44', 'bankcard', 'complete');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (9, 9, 'Grange', 'Josifovitz', '0762 Surrey Court', null, null, '19-305', 'Ełk', 'gjosifovitz8@about.com', '628-411-2254', null, '2018-11-24 11:55:22', 'diners-club-enroute', 'pending');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (10, 10, 'Burl', 'Domengue', '1 Messerschmidt Hill', null, null, null, 'Ljukovo', 'bdomengue9@ask.com', '679-935-8279', null, '2019-09-18 20:30:43', 'diners-club-enroute', 'inactive');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (11, 11, 'Daveen', 'Seager', '4905 Scoville Crossing', null, null, null, 'Sukaharja', 'dseagera@blogspot.com', '493-761-8692', null, '2019-11-10 12:03:03', 'jcb', 'pending');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (12, 12, 'Maitilde', 'Bullan', '692 Monterey Trail', null, null, null, 'San Antonio', 'mbullanb@yelp.com', '344-516-0430', null, '2019-07-29 19:30:34', 'jcb', 'pending');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (13, 13, 'Darsey', 'Orknay', '504 Susan Plaza', null, null, null, 'Huanuni', 'dorknayc@upenn.edu', '500-396-1310', null, '2019-05-20 11:29:23', 'diners-club-carte-blanche', 'complete');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (14, 14, 'Butch', 'Jolland', '7 Shoshone Crossing', null, null, null, 'Bicaj', 'bjollandd@dion.ne.jp', '393-795-3358', null, '2018-12-15 23:04:17', 'maestro', 'inactive');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (15, 15, 'Kinsley', 'Nore', '98 Badeau Place', null, null, null, 'Al Madān', 'knoree@yale.edu', '323-813-8337', null, '2019-03-21 01:17:32', 'jcb', 'complete');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (16, 16, 'Abra', 'Karet', '492 Sugar Place', null, null, null, 'Luoshui', 'akaretf@hhs.gov', '646-343-1871', null, '2019-07-13 18:01:14', 'americanexpress', 'complete');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (17, 17, 'Susana', 'Hawking', '7271 Dapin Center', null, null, '8407', 'Villa La Angostura', 'shawkingg@ftc.gov', '516-178-0041', null, '2019-03-16 19:10:36', 'americanexpress', 'complete');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (18, 18, 'Leonanie', 'Strattan', '589 Daystar Crossing', null, null, '472 01', 'Doksy', 'lstrattanh@e-recht24.de', '721-686-1990', null, '2019-07-12 04:20:34', 'jcb', 'inactive');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (19, 19, 'Gretta', 'Boothebie', '82940 Westridge Way', null, null, null, 'Nangtang', 'gboothebiei@goo.gl', '864-582-5543', null, '2019-08-20 06:58:09', 'switch', 'inactive');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (20, 20, 'Dare', 'Coppard', '277 Darwin Road', null, null, null, 'Shajing', 'dcoppardj@time.com', '560-439-2969', null, '2019-10-13 07:51:15', 'visa-electron', 'complete');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (21, 21, 'Olin', 'Cluitt', '56507 Di Loreto Road', null, null, '68721-000', 'Salinópolis', 'ocluittk@hubpages.com', '165-497-5712', null, '2019-03-09 21:23:57', 'mastercard', 'inactive');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (22, 22, 'Alastair', 'Wringe', '25 Columbus Street', null, false, 'L74', 'Liverpool', 'awringel@wunderground.com', '317-833-2575', null, '2018-12-29 12:34:55', 'jcb', 'pending');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (23, 23, 'Nanci', 'Byrcher', '4968 Eliot Lane', null, null, '47-470', 'Krzanowice', 'nbyrcherm@newsvine.com', '779-705-9626', null, '2019-01-19 17:02:14', 'switch', 'complete');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (24, 24, 'Waverly', 'Masey', '96 Oak Valley Circle', null, false, null, 'Panaoti', 'wmaseyn@auda.org.au', '145-841-1197', null, '2019-04-30 00:04:14', 'jcb', 'complete');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (25, 25, 'Drugi', 'Leathes', '00346 Mayfield Junction', null, null, '2065-114', 'Quebradas', 'dleatheso@nymag.com', '505-103-5976', null, '2019-10-09 14:59:34', 'switch', 'inactive');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (26, 26, 'Frederich', 'Aucutt', '51 Stuart Plaza', null, null, '8513', 'Esperanza', 'faucuttp@netscape.com', '787-660-1685', null, '2018-12-29 05:45:45', 'diners-club-carte-blanche', 'complete');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (27, 27, 'Barbabas', 'Ludlem', '35395 Hanover Crossing', null, null, '60028', 'Mastaiciai', 'bludlemq@cocolog-nifty.com', '838-873-5068', null, '2019-07-08 06:58:37', 'maestro', 'complete');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (28, 28, 'Alan', 'Tall', '78908 Northfield Terrace', null, null, null, 'Linxi', 'atallr@gnu.org', '709-443-6533', null, '2018-12-06 23:05:03', 'americanexpress', 'pending');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (29, 29, 'Donnell', 'Kippen', '30398 David Center', null, null, null, 'Pemba', 'dkippens@mlb.com', '505-435-5377', null, '2018-11-17 10:30:54', 'diners-club-enroute', 'complete');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (30, 30, 'Joane', 'Garmey', '8867 Fisk Avenue', null, null, '696 81', 'Bzenec', 'jgarmeyt@china.com.cn', '536-481-7304', null, '2019-08-09 16:46:13', 'maestro', 'inactive');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (31, 31, 'Jacintha', 'Matzaitis', '8 Park Meadow Alley', null, null, null, 'Kosonsoy', 'jmatzaitisu@hud.gov', '538-369-8068', null, '2019-09-07 22:03:14', 'jcb', 'complete');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (32, 32, 'Randee', 'Griffe', '3 Northfield Terrace', null, null, null, 'Shaliangzi', 'rgriffev@imgur.com', '334-782-9969', null, '2018-12-17 06:31:38', 'jcb', 'complete');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (33, 33, 'Cassius', 'Matuszak', '84 3rd Plaza', null, null, null, 'Ertai', 'cmatuszakw@bloomberg.com', '349-906-3262', null, '2019-03-24 21:06:42', 'jcb', 'complete');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (34, 34, 'Sara', 'Creak', '0 Blaine Parkway', null, null, '65170', 'Chat Trakan', 'screakx@blog.com', '348-999-3941', null, '2019-07-26 09:10:24', 'jcb', 'complete');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (35, 35, 'Hanson', 'Frape', '0995 Southridge Crossing', null, null, null, 'Beijie', 'hfrapey@wired.com', '668-399-0421', null, '2018-11-27 07:06:55', 'mastercard', 'complete');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (36, 36, 'Ingra', 'McKevin', '88045 Haas Avenue', null, null, '99-150', 'Grabów', 'imckevinz@nba.com', '359-112-3182', null, '2018-11-29 09:20:57', 'jcb', 'pending');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (37, 37, 'Price', 'Rainard', '17302 Buhler Street', null, null, '0712', 'Oslo', 'prainard10@stanford.edu', '594-916-3947', null, '2019-09-26 12:15:46', 'switch', 'complete');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (38, 38, 'Shem', 'Kilbourne', '78 Ridgeway Plaza', null, null, '57609 CEDEX', 'Forbach', 'skilbourne11@tamu.edu', '508-584-4588', null, '2019-07-18 21:07:03', 'jcb', 'inactive');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (39, 39, 'Tamarra', 'Kilner', '2062 Parkside Avenue', null, null, '36-100', 'Kolbuszowa', 'tkilner12@businessinsider.com', '206-231-8135', null, '2019-04-03 01:24:13', 'visa-electron', 'complete');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (40, 40, 'Anya', 'Sisselot', '3718 Ludington Hill', null, null, null, 'Pomabamba', 'asisselot13@upenn.edu', '795-958-4192', null, '2019-11-02 00:54:53', 'bankcard', 'inactive');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (41, 1, 'Claudette', 'Fintoph', '8 Roth Park', null, null, null, 'Ponjen', 'cfintoph14@yelp.com', '149-907-0161', null, '2019-07-04 03:09:48', 'diners-club-enroute', 'complete');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (42, 2, 'Donnajean', 'Folli', '67 Thompson Pass', null, null, null, 'Neochórion', 'dfolli15@woothemes.com', '268-794-5658', null, '2019-08-21 00:57:53', 'jcb', 'complete');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (43, 3, 'Darice', 'Dymidowicz', '68 Dottie Court', null, null, null, 'Debeljača', 'ddymidowicz16@com.com', '921-399-5035', null, '2018-12-23 09:23:41', 'jcb', 'inactive');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (44, 4, 'Frasier', 'Kulicke', '49198 Spenser Alley', null, null, 'L-5431', 'Lenningen', 'fkulicke17@ted.com', '369-620-6840', null, '2019-05-13 03:52:42', 'visa-electron', 'complete');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (45, 5, 'Rodolphe', 'Rumming', '090 Heath Hill', null, null, null, 'Kiambu', 'rrumming18@scientificamerican.com', '520-574-0013', null, '2019-05-25 00:21:37', 'switch', 'pending');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (46, 6, 'Alice', 'Bukac', '6 Surrey Junction', null, null, null, 'Anjiang', 'abukac19@youtube.com', '108-926-6650', null, '2019-07-13 02:17:42', 'mastercard', 'complete');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (47, 7, 'Glad', 'Malek', '139 Pawling Terrace', null, null, '40128', 'Bologna', 'gmalek1a@hubpages.com', '478-557-6658', null, '2019-04-12 20:06:35', 'solo', 'complete');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (48, 8, 'Dylan', 'Wrankling', '84 Village Green Drive', null, null, null, 'Xiangrong', 'dwrankling1b@devhub.com', '135-768-6420', null, '2019-09-15 22:34:22', 'switch', 'complete');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (49, 9, 'Erda', 'Ripping', '0481 Onsgard Plaza', null, null, null, 'Tunasbaru', 'eripping1c@hatena.ne.jp', '688-928-6312', null, '2019-04-01 23:41:13', 'jcb', 'complete');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (50, 10, 'Haslett', 'Prudham', '20 Raven Parkway', null, null, '647341', 'Dikson', 'hprudham1d@java.com', '460-927-4463', null, '2019-05-27 19:05:50', 'jcb', 'complete');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (51, 11, 'Elvira', 'Le Barr', '63531 Tennyson Hill', null, null, '303154', 'Znamenskoye', 'elebarr1e@issuu.com', '114-592-3881', null, '2019-06-26 10:12:32', 'diners-club-enroute', 'complete');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (52, 12, 'Kylila', 'Ryam', '34032 Cascade Park', null, null, null, 'Mantingantengah', 'kryam1f@multiply.com', '854-995-7731', null, '2019-01-31 23:51:39', 'diners-club-us-ca', 'pending');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (53, 13, 'Jemmie', 'Lingner', '8 Cardinal Circle', null, null, null, 'Laocheng', 'jlingner1g@geocities.jp', '166-844-3423', null, '2019-02-03 00:01:42', 'americanexpress', 'complete');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (54, 14, 'Jasmin', 'Kuschke', '7 Commercial Junction', null, null, '273058', 'Nóvita', 'jkuschke1h@comsenz.com', '193-866-0238', null, '2019-05-27 18:49:00', 'jcb', 'inactive');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (55, 15, 'Binky', 'Sheringham', '4 Northland Avenue', null, null, 'B4H', 'Amherst', 'bsheringham1i@joomla.org', '102-879-3396', null, '2019-03-28 01:38:27', 'china-unionpay', 'pending');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (56, 16, 'Darsie', 'Smurfit', '2 Dakota Point', null, null, '452778', 'Tuymazy', 'dsmurfit1j@gov.uk', '346-424-6366', null, '2019-03-14 18:41:56', 'americanexpress', 'pending');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (57, 17, 'Nissa', 'Manolov', '6 Eagan Center', null, null, null, 'Shuangfeng', 'nmanolov1k@shinystat.com', '700-514-2480', null, '2019-05-10 02:48:33', 'switch', 'complete');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (58, 18, 'Sallyann', 'Oxley', '306 6th Road', null, null, '614532', 'Froly', 'soxley1l@constantcontact.com', '615-567-4717', null, '2019-05-13 15:44:03', 'americanexpress', 'complete');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (59, 19, 'Eadie', 'Sonnenschein', '08923 Kipling Road', null, null, '69110-000', 'Mogi das Cruzes', 'esonnenschein1m@geocities.com', '413-495-4051', null, '2019-05-11 21:08:15', 'maestro', 'complete');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (60, 20, 'Heddie', 'Bromont', '9102 Atwood Drive', null, null, null, 'Pameungpeuk', 'hbromont1n@businessweek.com', '668-915-2341', null, '2018-12-12 06:28:50', 'jcb', 'pending');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (61, 21, 'Noe', 'Trask', '21797 Sauthoff Avenue', null, null, null, 'Karangturi', 'ntrask1o@forbes.com', '241-105-4748', null, '2019-01-21 07:39:05', 'jcb', 'pending');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (62, 22, 'Neila', 'Matzaitis', '052 Straubel Avenue', null, null, '29690-000', 'Itaguaçu', 'nmatzaitis1p@uol.com.br', '624-933-6485', null, '2019-08-12 13:27:42', 'mastercard', 'complete');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (63, 23, 'Alano', 'Guerri', '78 Leroy Drive', null, null, null, 'Quşrah', 'aguerri1q@theguardian.com', '512-259-5093', null, '2019-06-20 15:43:18', 'bankcard', 'complete');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (64, 24, 'Nicko', 'Aldersley', '43920 Declaration Trail', null, null, null, 'Koni-Djodjo', 'naldersley1r@ftc.gov', '667-315-6560', null, '2019-08-08 09:25:12', 'jcb', 'complete');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (65, 25, 'Derward', 'Wakefield', '063 Schmedeman Street', null, false, '11254', 'Brooklyn', 'dwakefield1s@google.nl', '212-985-9588', null, '2019-02-06 21:39:06', 'laser', 'complete');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (66, 26, 'Sholom', 'Witard', '8 Harper Hill', null, null, '170 66', 'Solna', 'switard1t@auda.org.au', '326-179-7187', null, '2019-04-25 07:05:08', 'maestro', 'inactive');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (67, 27, 'Laney', 'Prout', '073 Northview Avenue', null, null, '636708', 'Kargasok', 'lprout1u@loc.gov', '458-203-0536', null, '2019-09-16 23:34:44', 'jcb', 'pending');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (68, 28, 'Marice', 'Gorler', '4695 Hansons Way', null, null, null, 'Xinyi', 'mgorler1v@clickbank.net', '784-979-4080', null, '2019-03-12 09:57:27', 'mastercard', 'pending');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (69, 29, 'Tobey', 'Vasyagin', '5033 Bunker Hill Street', null, false, null, 'Pelasgía', 'tvasyagin1w@amazon.com', '983-311-2513', null, '2019-08-13 02:34:50', 'maestro', 'complete');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (70, 30, 'Anastasia', 'Cosser', '47284 Lakewood Point', null, false, null, 'Bakhmach', 'acosser1x@hp.com', '513-908-4500', null, '2019-01-04 05:47:35', 'jcb', 'complete');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (71, 31, 'Jerrold', 'Newlyn', '62981 Farwell Point', null, null, '33448', 'Delray Beach', 'jnewlyn1y@ted.com', '561-488-6318', null, '2019-06-25 13:52:11', 'visa', 'inactive');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (72, 32, 'Karlens', 'Barok', '68185 Fuller Alley', null, null, null, 'Traiguén', 'kbarok1z@harvard.edu', '286-454-4450', null, '2019-07-09 02:36:04', 'diners-club-carte-blanche', 'complete');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (73, 33, 'Thom', 'Boneham', '8964 Linden Plaza', null, null, '21051 CEDEX', 'Dijon', 'tboneham20@free.fr', '331-212-4581', null, '2019-10-27 21:37:48', 'maestro', 'inactive');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (74, 34, 'Mair', 'Ervine', '7705 Rusk Alley', null, null, '331 43', 'Värnamo', 'mervine21@mlb.com', '858-192-0930', null, '2019-10-01 03:28:23', 'jcb', 'complete');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (75, 35, 'Piper', 'Postans', '9 Grasskamp Drive', null, null, null, 'Kukuna', 'ppostans22@devhub.com', '244-341-1236', null, '2019-07-05 09:38:13', 'visa-electron', 'pending');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (76, 36, 'Arturo', 'Mingardo', '9 Milwaukee Terrace', null, null, null, 'Weekaka', 'amingardo23@live.com', '599-174-5694', null, '2019-02-08 20:17:52', 'jcb', 'complete');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (77, 37, 'Dasya', 'Durand', '894 Westerfield Road', null, null, '1079', 'Amsterdam Oud Zuid en Rivierenbuurt', 'ddurand24@vinaora.com', '951-138-0224', null, '2019-01-14 05:44:39', 'instapayment', 'complete');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (78, 38, 'Odo', 'Mocher', '238 Hollow Ridge Alley', null, null, null, 'Yuexi', 'omocher25@home.pl', '319-968-4526', null, '2019-05-19 17:23:42', 'jcb', 'inactive');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (79, 39, 'Tammy', 'Abrahmovici', '475 Thompson Circle', null, null, '5507', 'Looc', 'tabrahmovici26@multiply.com', '629-656-6192', null, '2019-03-02 10:53:58', 'laser', 'complete');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (80, 40, 'Sam', 'Maunsell', '82 Thackeray Way', null, null, '51074 CEDEX', 'Reims', 'smaunsell27@bluehost.com', '299-857-7419', null, '2019-08-25 21:42:27', 'jcb', 'inactive');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (81, 1, 'Ruddie', 'Smidmore', '474 Brentwood Parkway', null, null, '13281 CEDEX 06', 'Marseille', 'rsmidmore28@technorati.com', '164-715-8907', null, '2019-05-06 01:49:06', 'visa', 'inactive');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (82, 2, 'Janna', 'Plant', '513 Jenifer Road', null, null, null, 'Tunis', 'jplant29@unblog.fr', '763-939-2010', null, '2019-05-28 15:42:19', 'jcb', 'complete');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (83, 3, 'Tyrus', 'Birwhistle', '91 Sheridan Hill', null, null, null, 'Qingsong', 'tbirwhistle2a@alibaba.com', '956-626-1252', null, '2019-11-10 20:41:03', 'jcb', 'complete');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (84, 4, 'Shelia', 'Rupel', '5684 Monument Center', null, null, null, 'Oodweyne', 'srupel2b@umn.edu', '166-722-9754', null, '2019-05-26 05:43:29', 'jcb', 'complete');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (85, 5, 'Dall', 'Mashro', '07 Oakridge Drive', null, null, null, 'Dubno', 'dmashro2c@soup.io', '132-917-2675', null, '2018-12-18 18:42:42', 'jcb', 'complete');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (86, 6, 'Sissy', 'Muglestone', '3684 Pankratz Place', null, null, null, 'Madona', 'smuglestone2d@nifty.com', '654-250-6083', null, '2018-12-09 17:34:35', 'jcb', 'complete');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (87, 7, 'Yoshiko', 'Morgans', '5 3rd Point', null, false, null, 'Negara', 'ymorgans2e@dot.gov', '500-905-6278', null, '2019-10-16 01:26:17', 'instapayment', 'pending');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (88, 8, 'Winnie', 'Themann', '50 Sutteridge Pass', null, null, null, 'Nyanga', 'wthemann2f@toplist.cz', '577-666-5874', null, '2019-10-13 03:57:40', 'laser', 'pending');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (89, 9, 'Lorianne', 'Rudham', '3 Briar Crest Junction', null, null, '989-2474', 'Asahi', 'lrudham2g@jigsy.com', '745-209-0237', null, '2019-07-26 03:39:17', 'switch', 'inactive');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (90, 10, 'Norbert', 'Rasp', '1358 Comanche Way', null, null, null, 'Macheng', 'nrasp2h@ihg.com', '456-272-3822', null, '2019-02-04 11:49:31', 'jcb', 'inactive');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (91, 11, 'Duff', 'McCallister', '2 Morrow Center', null, null, null, 'Boafeo', 'dmccallister2i@blogspot.com', '298-804-9714', null, '2019-04-15 04:43:19', 'jcb', 'pending');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (92, 12, 'Wernher', 'Rippin', '54089 Barnett Plaza', null, null, '0921', 'Pidsandawan', 'wrippin2j@addtoany.com', '410-462-5228', null, '2019-01-26 05:45:47', 'mastercard', 'complete');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (93, 13, 'Edsel', 'Hamlen', '90260 Mcbride Center', null, false, '6419', 'San Vicente', 'ehamlen2k@dion.ne.jp', '396-351-4882', null, '2019-01-15 09:09:28', 'jcb', 'inactive');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (94, 14, 'Adelaide', 'Pettisall', '9911 Packers Court', null, null, null, 'Changqing', 'apettisall2l@forbes.com', '531-567-4010', null, '2018-12-04 21:35:55', 'mastercard', 'complete');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (95, 15, 'Alfonse', 'Borrington', '83762 Monument Crossing', null, null, null, 'Béboto', 'aborrington2m@artisteer.com', '754-235-1321', null, '2019-05-09 21:33:57', 'jcb', 'pending');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (96, 16, 'Cele', 'Brimmacombe', '90707 Homewood Terrace', null, null, '68540', 'San Miguel', 'cbrimmacombe2n@pcworld.com', '266-435-7337', null, '2019-06-12 19:50:56', 'jcb', 'pending');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (97, 17, 'Elset', 'Capoun', '75512 Lukken Lane', null, null, '662955', 'Krasnokamensk', 'ecapoun2o@archive.org', '373-306-6270', null, '2019-01-18 08:00:30', 'diners-club-enroute', 'inactive');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (98, 18, 'Ajay', 'Claasen', '49115 Jenifer Road', null, null, null, 'Gamboula', 'aclaasen2p@constantcontact.com', '170-574-2930', null, '2019-03-12 10:15:00', 'americanexpress', 'complete');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (99, 19, 'Elmer', 'Harme', '85 Debs Circle', null, false, null, 'Hekou', 'eharme2q@earthlink.net', '334-738-3753', null, '2019-10-01 22:02:02', 'china-unionpay', 'complete');
insert into orders (id, country_id, first_name, last_name, street_address1, street_address2, province, postal_code, city, email_address, phone_number, company, payment_timestamp, payment_method, payment_status) values (100, 20, 'Tomasine', 'Meiklem', '02067 Clove Road', null, null, '6201', 'Sibulan', 'tmeiklem2r@webmd.com', '736-488-2918', null, '2018-12-04 09:13:17', 'jcb', 'complete');
