CREATE TABLE series (
  id INTEGER NOT NULL PRIMARY KEY,
  title VARCHAR(100) NOT NULL,
  subtitle VARCHAR(100) NOT NULL,
  quantity INTEGER NOT NULL,
  year DATE NOT NULL,
  description TEXT NOT NULL,
  dimensions VARCHAR(50),
  medium VARCHAR(50)
);
insert into series (id, title, subtitle, quantity, year, description, dimensions, medium) values (1, 'Monte Guilarte Hollyfern', 'Dryopteridaceae', 70, '5/31/2019', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', '34x69cm', 'Losartan Potassium and Hydrochlorothiazide');
insert into series (id, title, subtitle, quantity, year, description, dimensions, medium) values (2, 'Lapham''s Phlox', 'Polemoniaceae', 89, '11/13/2019', 'Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.', '39x21cm', 'XEROSTOM');
insert into series (id, title, subtitle, quantity, year, description, dimensions, medium) values (3, 'Yellow Thistle', 'Asteraceae', 82, '8/24/2019', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', '90x59cm', 'Phenytoin');
insert into series (id, title, subtitle, quantity, year, description, dimensions, medium) values (4, 'Nealley''s Kisses', 'Onagraceae', 49, '9/1/2019', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.', '30x69cm', 'Heparin Sodium');
insert into series (id, title, subtitle, quantity, year, description, dimensions, medium) values (5, 'Mountain Ashdaisy', 'Asteraceae', 80, '6/16/2019', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.', '79x36cm', 'Acid Free-Flux');
insert into series (id, title, subtitle, quantity, year, description, dimensions, medium) values (6, 'Schweinitz''s Sedge', 'Cyperaceae', 57, '8/7/2019', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', '48x79cm', 'Moore Medical Antacid');
insert into series (id, title, subtitle, quantity, year, description, dimensions, medium) values (7, 'Arizona Rush', 'Juncaceae', 27, '6/16/2019', 'Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum.', '68x13cm', 'Italian Rye Grass');
insert into series (id, title, subtitle, quantity, year, description, dimensions, medium) values (8, 'Hybrid Violet', 'Violaceae', 67, '2/1/2019', 'Etiam justo.', '53x40cm', 'Acetazolamide');
insert into series (id, title, subtitle, quantity, year, description, dimensions, medium) values (9, 'Lemmon''s Lessingia', 'Asteraceae', 61, '11/13/2019', 'Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla.', '57x02cm', 'Haloperidol');
insert into series (id, title, subtitle, quantity, year, description, dimensions, medium) values (10, 'Twining Bluehood', 'Fabaceae', 26, '2/13/2019', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius.', '99x21cm', 'Metoprolol Tartrate');
insert into series (id, title, subtitle, quantity, year, description, dimensions, medium) values (11, 'Fan Spikemoss', 'Selaginellaceae', 62, '7/2/2019', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.', '13x24cm', 'Goose Feathers');
insert into series (id, title, subtitle, quantity, year, description, dimensions, medium) values (12, 'John Charles', 'Lamiaceae', 98, '8/30/2019', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', '82x52cm', 'Tolterodine Tartrate');
insert into series (id, title, subtitle, quantity, year, description, dimensions, medium) values (13, 'Hausa Potato', 'Lamiaceae', 77, '6/6/2019', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', '97x72cm', 'Glimepiride');
insert into series (id, title, subtitle, quantity, year, description, dimensions, medium) values (14, 'Siskiyou Sedge', 'Cyperaceae', 41, '9/2/2019', 'Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.', '23x94cm', 'Anticavity Fluoride Rinse');
insert into series (id, title, subtitle, quantity, year, description, dimensions, medium) values (15, 'Howell''s Fawnlily', 'Liliaceae', 36, '6/12/2019', 'Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', '40x65cm', 'Hydrocodone Bitartrate And Acetaminophen');
insert into series (id, title, subtitle, quantity, year, description, dimensions, medium) values (16, 'Nevada Pottia Moss', 'Pottiaceae', 79, '12/14/2018', 'Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor.', '20x95cm', 'Oxygen');
insert into series (id, title, subtitle, quantity, year, description, dimensions, medium) values (17, 'Crescent Buckwheat', 'Polygonaceae', 84, '6/1/2019', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.', '53x13cm', 'SINGULAIR');
insert into series (id, title, subtitle, quantity, year, description, dimensions, medium) values (18, 'Blue Wildrye', 'Poaceae', 38, '6/21/2019', 'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', '16x34cm', 'Solar Sense Zany Zinc SPF 50 - Blue');
insert into series (id, title, subtitle, quantity, year, description, dimensions, medium) values (19, 'Adelolecia Lichen', 'Bacidiaceae', 73, '1/10/2019', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', '61x94cm', 'HYZAAR');
insert into series (id, title, subtitle, quantity, year, description, dimensions, medium) values (20, 'Plains Flax', 'Linaceae', 77, '6/23/2019', 'Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.', '78x01cm', 'good sense cold');
insert into series (id, title, subtitle, quantity, year, description, dimensions, medium) values (21, 'Oahu Sedge', 'Cyperaceae', 90, '8/29/2019', 'Nulla facilisi. Cras non velit nec nisi vulputate nonummy.', '11x85cm', 'Carisoprodol');
insert into series (id, title, subtitle, quantity, year, description, dimensions, medium) values (22, 'Long''s Blackberry', 'Rosaceae', 95, '4/21/2019', 'Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', '86x71cm', 'Ondansetron');
insert into series (id, title, subtitle, quantity, year, description, dimensions, medium) values (23, 'Sierra Laurel', 'Ericaceae', 25, '11/2/2019', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.', '65x61cm', 'Norvir');
insert into series (id, title, subtitle, quantity, year, description, dimensions, medium) values (24, 'Fleshy Beardtongue', 'Scrophulariaceae', 62, '7/15/2019', 'Morbi vel lectus in quam fringilla rhoncus.', '96x14cm', 'Mattifying Day Moisture Broad Spectrum SPF 15');
insert into series (id, title, subtitle, quantity, year, description, dimensions, medium) values (25, 'Georgia False Indigo', 'Fabaceae', 49, '8/2/2019', 'Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit.', '36x29cm', 'White Oak');
insert into series (id, title, subtitle, quantity, year, description, dimensions, medium) values (26, 'Gander''s Buckhorn Cholla', 'Cactaceae', 56, '10/24/2019', 'Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.', '14x69cm', 'all day allergy relief');
insert into series (id, title, subtitle, quantity, year, description, dimensions, medium) values (27, 'Irregular Polypody', 'Polypodiaceae', 87, '12/4/2018', 'Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus.', '19x19cm', 'Canary Grass');
insert into series (id, title, subtitle, quantity, year, description, dimensions, medium) values (28, 'Small Spreading Pogonia', 'Orchidaceae', 1, '4/9/2019', 'Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque.', '42x23cm', 'Oxycodone and Acetaminophen');
insert into series (id, title, subtitle, quantity, year, description, dimensions, medium) values (29, 'Flavopunctelia Lichen', 'Parmeliaceae', 41, '8/6/2019', 'Nullam molestie nibh in lectus.', '77x62cm', 'Omeprazole');
insert into series (id, title, subtitle, quantity, year, description, dimensions, medium) values (30, 'Mountain Holly', 'Aquifoliaceae', 68, '4/24/2019', 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', '92x03cm', 'Valsartan and Hydrochlorothiazide');
